class LoginModuleResources:
    username = "//input[@id='name']"
    password = "//input[@id='password']"
    submit_button = "//button[@id='submitSigninLogin']"
    popup = "//*[@id='popUpMessage']"

class UserModuleResources:
    User_Module = "//a[normalize-space()='Users']"
    Add_New_User_Btn = "//a[@onclick='ClearFields();']"
    User_Name = "//input[@id='user_username']"
    User_popup_1 = "//*[@id='usernamespace']"
    position = "//option[@value='3,manager']"
    Email  = "//*[@id='email']"
    Email_popup = "//*[@id='email-pattern']"
    Password = "//*[@id='password']"
    Password_popup = "//*[@id='passwordNotMatch-id-first']"
    Password1 = "//*[@id='password1']"
    Password_popup1 = "//*[@id='error-id-first']"
    Second_Correct_Password = "//*[@id='success-id-first']"
    Add_User_Btn = "//*[@id='form_submit']"
    Create_User_popup = "//*[@id='popUpMessage']"
    Search_User = "//*[@id='searchText']"
    Three_Dots = "//*[@class='assign-compaign-btn']"
    User_Details = "//*[@class='active']"
